version: 2
updates:
  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: maven
    directory: /examples/jms
    schedule:
      interval: weekly

  - package-ecosystem: maven
    directory: /examples/kafka
    schedule:
      interval: weekly

  - package-ecosystem: maven
    directory: /examples/pulsar
    schedule:
      interval: weekly
